default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  hostname: localhost
  database: trips
  username: dev
  password: 123654

test: &test
  <<: *default
  hostname: localhost
  database: trips_test
  username: dev
  password: 123654


production:
  <<: *default
    hostname: localhost
    database: trips_prod
    username: dev
    password: 123654

cucumber:
  <<: *test
